-- src/main/resources/db/migration/v1__init.sql
CREATE TABLE authors(
    author_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    , author_name VARCHAR (20) NOT NULL
    , birth_date DATE NOT NULL
    , created_at TIMESTAMP NOT NULL DEFAULT now()
    , updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE books(
    book_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
    , author_id INTEGER NOT NULL REFERENCES authors(author_id)
    , title VARCHAR (100) NOT NULL
    , price SMALLINT NOT NULL DEFAULT 0
    , publication_status VARCHAR (20) NOT NULL DEFAULT 'UNPUBLISHED'
    , created_at TIMESTAMP NOT NULL DEFAULT now()
    , updated_at TIMESTAMP NOT NULL DEFAULT now()
);

CREATE INDEX idx_books_author ON books(author_id);
